version: '3'

services:
  # Cliente React
  client:
    build:
      #context: ./protectora_frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    depends_on:
      - api

  # API Laravel
  api:
    build:
      #context: ./protectora_backend
      dockerfile: Dockerfile-backend
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80 || exit 1"]
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    command: ["sh", "-c", "apache2-foreground"]
